name: gdeploy test

on:
  schedule:
    - cron: 0 23 * * *
  workflow_dispatch:
    inputs:
    
jobs:
  test1:
    runs-on: ubuntu-latest
    name: Test1 Sync
    continue-on-error: true
    timeout-minutes: 200

    steps:
      - uses: actions/checkout@v2
      - name: Test Install
        run: |
          sudo add-apt-repository ppa:qbittorrent-team/qbittorrent-stable
          sudo apt install qbittorrent-nox
          wget https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-amd64.deb
          sudo dpkg -i cloudflared-stable-linux-amd64.deb
          mkdir -p /home/runner/.config/qBittorrent/
          sudo cp qBittorrent.conf /home/runner/.config/qBittorrent
          cd ~/
          mkdir .cloudflared
          cd .cloudflared
          cat << EOF >> cert.pem
          ${{ secrets.CF_CERT }}
          EOF
          cd ..
          qbittorrent-nox & cloudflared tunnel --url localhost:8080 --hostname ${{ secrets.DOMAIN }}
